//////////////////////////////////////////////////////////////////////
//
//  Copyright:
//        Your Copyright goes here., (c) 2000. All rights reserved.
//
//  Contents:
//        This is a standard win32 exe.
//
//////////////////////////////////////////////////////////////////////

#include "Common.ch"

/* Overloaded AppSys which does nothing
 */
PROCEDURE AppSys

   /* use the ANSI charset by default */
   SET CHARSET TO ANSI

   /* $TODO: create your application container here */
RETURN

/* This is our main procedure
 */
PROCEDURE Main

   /*
   ** $TODO: create your application logic here
   */

RETURN
