//////////////////////////////////////////////////////////////////////
//
//  Copyright:
//        Your Copyright goes here., (c) 2000. All rights reserved.
//
//  Contents:
//        This is a standard console mode exe.
//
//////////////////////////////////////////////////////////////////////

#include "common.ch"

/* This is our main procedure
 */
PROCEDURE Main

   /* we use the ansi charset by default */
   SET CHARSET TO ANSI

   /* $TODO: place your application code here */
RETURN
